[package]
name = "nalgebra_linsys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31.0"
thiserror = "1.0.31"

[dev-dependencies]
num-rational = "0.4.0"
num-bigint = "0.4.3"